@Library('my-shared-library') _

pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script { dockerUtils.build("nouraabelnabi/FinalProject:${env.BUILD_ID}") }
            }
        }
        stage('Deploy') {
            steps {
                script { 
                    gitUtils.updateManifest('k8s/deploy.yml', "noura-abdelnabi/FinalProject:${env.BUILD_ID}")
                    gitUtils.pushChanges('github-creds')
                }
            }
        }
    }
}
