@Library('my-shared-library') _

pipeline {
    agent any
    tools {
        dockerTool 'default' 
    }
    stages {
        stage('Build') {
            steps {
                script { dockerUtils.build("nouraabelnabi/finalproject:${env.BUILD_ID}") }
            }
        }
        stage('Deploy') {
            steps {
                script { 
                    gitUtils.updateManifest('Ansible/k8s_deploy/files/deployment.yml', "nouraabdelnabi/finalproject:${env.BUILD_ID}")
                    gitUtils.pushChanges('githubcred')
                }
            }
        }
    }
}
