@Library('my-shared-library') _

pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script { dockerUtils.build("nouraabelnabi/FinalProject:${env.BUILD_ID}") }
            }
        }
        stage('Deploy') {
            steps {
                script { 
                    gitUtils.updateManifest('Ansible/k8s_deploy/files/deployment.yml', "nouraabdelnabi/FinalProject:${env.BUILD_ID}")
                    gitUtils.pushChanges('githubcred')
                }
            }
        }
    }
}
